version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app # Mount thư mục code vào container
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload # Auto-reload khi file thay đổi

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - fastapi
    restart: always
